
default: &default
  adapter: postgresql
  encoding: unicode
  database: mydb
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: myuser
  password: pass
  host: localhost

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: mydb
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: myuser
  password: pass
  host: localhost
